name: Deploy Cloudflare Worker

on:
  push:
    branches:
      - develop
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Wrangler
        run: npm install -g wrangler

      - name: Configure Cloudflare API token
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: echo "Cloudflare API Token configured"

      - name: Deploy Worker
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: |
          BRANCH_NAME=${GITHUB_REF##*/}
          echo "Detected branch: $BRANCH_NAME"

          if [ "$BRANCH_NAME" = "develop" ]; then
            echo "Deploying to DEV environment..."
            wrangler deploy --env dev || true
          elif [ "$BRANCH_NAME" = "main" ]; then
            echo "Deploying to PROD environment..."
            wrangler deploy --env prod || true
          else
            echo "Branch not configured for deployment. Skipping."
          fi
